laravelsource/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth'])->group(function () {
    Route::group([
        'as' => 'admin.',
        // 'middleware' => 'is_admin'
        'prefix' => 'admin'
    ],function () {
        Route::get('/', [\App\Http\Controllers\HomeController::class, 'index'])->name('home');
        Route::get('/logout', [\App\Http\Controllers\Auth\LoginController::class, 'logout']);

        // task
        Route::resource('/task', \App\Http\Controllers\Admin\TaskController::class);
        // Route::get('/task',[\App\Http\Controllers\Admin\TaskController::class, 'index'])->name('task.index');
        // Route::get('/create-task',[\App\Http\Controllers\Admin\TaskController::class, 'create'])->name('task.create');
        // Route::post('/create-task',[\App\Http\Controllers\Admin\TaskController::class, 'store'])->name('task.create');
        // Route::get('/edit-task/{id}',[\App\Http\Controllers\Admin\TaskController::class, 'edit'])->name('task.edit');
        // Route::post('/update-task',[\App\Http\Controllers\Admin\TaskController::class, 'update'])->name('task.update');
        // Route::get('/delete-task/{id}',[\App\Http\Controllers\Admin\TaskController::class, 'destroy'])->name('task.delete');

        // product
        Route::resource('/product', \App\Http\Controllers\Admin\ProductController::class);
    });
});
Route::get('/',fn() => redirect('admin/login'));
Route::get('/admin/login', function () {
    return view('admin.auth.login');
})->name('login');
Route::post('/admin/login', [\App\Http\Controllers\Auth\LoginController::class, 'login'])->name('login');

laravelsource/app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    use HasFactory;
    protected $table = 'tasks';

    /* match policy to use */
    // protected $policies = [
    //     User::class => App\Policies\ProjectPolicy::class,
    // ];
    protected $fillable = [
        'name',
        'description',
        'user_id'
    ];
    public function user(){
        return $this->belongsTo(User::class,'user_id','id');
    }
}

laravelsource/app/Http/Controllers/Admin/TaskController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Task;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['tasks'] = Task::OrderBy('id', 'DESC')->get();
        return view('admin.pages.tasks.index')->with($data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', Task::class);
        $data['users'] = User::where('role_id',3)->get();
        return view('admin.pages.tasks.create')->with($data);;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('create', Task::class);
        $credential = $request->validate([
            'name' => ['required'],
            'description' => ['required']
        ],[
            'name.required' => 'Name không được để trống',
            'description.required' => 'Description không được để trống'
        ]);
        if (Task::create(['name' => $request->name, 'description' => $request->description, 'user_id' => $request->user])){
            return redirect()->route('admin.task.index')->with('success','Task Created Successfully!!');
        }
  
        return back()->withErrors([
            'message' => 'Thêm thất bại vui lòng kiểm tra lại',
        ])->withinput();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['task'] = Task::find($id);
        $this->authorize('update', $data['task']);
        $data['users'] = User::where('role_id',3)->get();
        return view('admin.pages.tasks.edit')->with($data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $task = Task::find($request->id);
        $this->authorize('update', $task);
        $credential = $request->validate([
            'name' => ['required'],
            'description' => ['required']
        ],[
            'name.required' => 'Name không được để trống',
            'description.required' => 'Description không được để trống'
        ]);

        
        if ($task->update(["name" => $request->name, "description" => $request->description])){
            return redirect()->route('admin.task.index')->with('success','Task Created Successfully!!'); 
        }

        return back()->withErrors([
            'message' => 'Cập nhật thất bại vui lòng kiểm tra lại',
        ])->withinput();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $task = Task::find($id);
        $this->authorize('delete', $task);
        if ($task->delete()){
            return response()->json([
                'error'    => false,
                'messages' => "Xóa thành công",
            ], 200);
        }
        return response()->json([
            'error'    => true,
            'messages' => "Có lỗi xảy ra vui lòng thử lại",
        ], 200);
        
    }
}

laravelsource/resources/views/admin/pages/tasks/create.blade.php
@extends('admin.layouts.main',['title' => 'Create Task'])
@push('styles')
    {{-- <link rel="stylesheet" href="style.css"> --}}
    <style style="text/css">
        .content .block {
            width: 40%;
        }

        .selection .select2-selection {
            height: auto;
        }

        .select2-container--default .select2-selection--single .select2-selection__arrow {
            top: 8px;
            right: 15px;
        }

    </style>
@endpush
@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="mb-2 row">
                    <div class="col-sm-6">
                        <h1 class="m-0">Create Tasks</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Dashboard v1</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="block py-12 mx-auto">
                    <form action="{{ Route('admin.task.create') }}" method="POST">
                        @csrf
                        <div class="mb-3">
                            <label for="Name" class="form-label">Name</label>
                            <input type="text" class="form-control" name="name" value="{{ old('name') }}">
                        </div>
                        <div class="mb-3">
                            <label for="description" class="form-label">Description</label>
                            <input type="text" class="form-control" name="description" value="{{ old('description') }}">
                        </div>
                        <div class="mb-3">
                            <label for="user">User</label>
                            <select class="form-control selectoption" name="user">
                                @if ($users)
                                    @foreach ($users as $user)
                                        <option value="{{ $user->id }}">{{ $user->name }}</option>
                                    @endforeach
                                @endif;
                            </select>
                        </div>
                        <div class="mb-3 d-flex justify-content-end">
                            <button type="submit" class="btn btn-primary">Create</button>
                        </div>
                    </form>
                </div>
            </div>
            <!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
@endsection
@push('scripts')
    <script type="text/javascript">
        toastr.options = {
            "positionClass": "toast-top-center",
        }
        $(document).ready(function() {
            $('#myTable').DataTable();
            $('.selectoption').select2();
        });
        @if ($errors->any())
            @foreach ($errors->all() as $item)
                toastr.error('{{ $item }}', 'Thông báo!');
            @break
            @endforeach
        @endif
    </script>
@endpush

laravelsource/resources/views/admin/pages/tasks/edit.blade.php
@extends('admin.layouts.main',['title' => 'Create Task'])
@push('styles')
    {{-- <link rel="stylesheet" href="style.css"> --}}
    <style style="text/css">
        .content .block {
            width: 40%;
        }
        .selection .select2-selection {
            height: auto;
        }

        .select2-container--default .select2-selection--single .select2-selection__arrow {
            top: 8px;
            right: 15px;
        }
    </style>
@endpush
@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="mb-2 row">
                    <div class="col-sm-6">
                        <h1 class="m-0">Update Tasks</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Dashboard v1</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="block py-12 mx-auto">
                    <form action="{{ Route('admin.task.update') }}" method="POST">
                        @csrf
                        <input type="text" value="{{ $task->id }}" hidden name="id">
                        <div class="mb-3">
                            <label for="Name" class="form-label">Name</label>
                            <input type="text" class="form-control" name="name" value="{{ $task->name ?? '' }}">
                        </div>
                        <div class="mb-3">
                            <label for="description" class="form-label">Description</label>
                            <input type="text" class="form-control" name="description" value="{{ $task->description ?? '' }}">
                        </div>
                        <div class="mb-3">
                            <label for="user">User</label>
                            <select class="form-control selectoption" name="user">
                                @if ($users)
                                    @foreach ($users as $user)
                                        @if($user->id == $task->user_id)
                                            <option selected value="{{ $user->id }}">{{ $user->name }}</option>
                                        @else
                                            <option value="{{ $user->id }}">{{ $user->name }}</option>
                                        @endif
                                    @endforeach
                                @endif;
                            </select>
                        </div>
                        <div class="mb-3 d-flex justify-content-end">
                            <button type="submit" class="btn btn-primary">update</button>
                        </div>
                    </form>
                </div>
            </div>
            <!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
@endsection
@push('scripts')
    <script type="text/javascript">
        toastr.options = {"positionClass": "toast-top-center",}
        $(document).ready(function() {
            $('#myTable').DataTable();
            $('.selectoption').select2();
        });
        @if ($errors->any())
            @foreach ($errors->all() as $item)
                toastr.error('{{ $item }}', 'Thông báo!');
                @break
            @endforeach
        @endif
    </script>
@endpush

laravelsource/resources/views/admin/pages/tasks/index.blade.php
@extends('admin.layouts.main',['title' => 'Task'])
@push('styles')
{{-- <link rel="stylesheet" href="style.css"> --}}
<style style="text/css">
</style>
@endpush
@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="mb-2 row">
          <div class="col-sm-6">
            <h1 class="m-0">Tasks</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Dashboard v1</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="py-2 text-right right-button">
            @can('create', \App\Models\Task::class)
                <a href="{{ route('admin.task.create') }}" type="button" class="btn btn-primary">Create</a>
            @endcan
        </div>
        @if ($tasks)
          <table id="myTable" class="table table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>STT</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($tasks as $key => $task)
                    <tr>
                        @csrf
                        <td>{{ ++$key }}</td>
                        <td>{{ $task->name }}</td>
                        <td>{{ $task->description }}</td>
                        <td>
                            @can('update', $task)
                                <a href="{{ route('admin.task.edit',$task)}}" class="btn btn-primary">edit</a>
                            @endcan
                            @can('delete',$task)
                                <button class="btn btn-danger delete" data-id="{{ $task->id }}">delete</button>
                            @endcan
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
        @endif
       
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection
@push('scripts')
<script type="text/javascript">
    $(document).ready( function () {
        $('#myTable').DataTable();
    }); 
    $('.delete').click( function (){
      let id = $(this).data('id');
      var element = $(this).parent().parent();
      var token = $("meta[name='csrf-token']").attr("content");
      bootbox.confirm("Bạn có chắc chắn muốn xóa?", function(result){
        if (result){
          $.ajax({
            url: "/admin/task",
            type: 'DELETE',
            data: {
              _token: token,
              id: id
            },
            success: function (response) {
              toastr.success(response['messages'], "Thông báo");
              element.remove();
            },
            error: function (response) {
              toastr.error(response['messages'], 'Thông báo!');
            }
        }); 
        }
      });
    });
</script>
@endpush